version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    environment:
      - DATABASE_URL=sqlite:///./chat.db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3005:3005"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
